function d_tau_d_phi1 = d_tau_d_phi1(rho1,rho2,rho3,phi1,phi2,phi3,Gx,Gy,Gz)
%D_TAU_D_PHI1
%    D_TAU_D_PHI1 = D_TAU_D_PHI1(RHO1,RHO2,RHO3,PHI1,PHI2,PHI3,Gx,Gy,Gz)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    22-Oct-2024 02:10:02

t2 = abs(phi1);
t3 = abs(phi2);
t4 = abs(phi3);
t5 = sign(phi1);
t6 = Gx.^2;
t7 = Gy.^2;
t8 = phi1.^2;
t9 = phi2.^2;
t10 = phi3.^2;
t11 = t2.^2;
t12 = t3.^2;
t13 = t4.^2;
t14 = t8+t9+t10;
t15 = t11+t12+t13;
t16 = sqrt(t14);
t88 = t14.*1.0e+10;
t20 = 1.0./t15;
t22 = sqrt(t15);
t28 = (t16 < 1.0e-5);
t91 = (1.0 < t88);
t21 = t20.^2;
t23 = 1.0./t22;
t25 = cos(t22);
t26 = sin(t22);
t24 = t23.^3;
t27 = t25-1.0;
t29 = t23.*t26;
t34 = t2.*t5.*t20.*t25;
t30 = t20.*t27;
t31 = phi1.*t29;
t32 = phi2.*t29;
t33 = phi3.*t29;
t38 = -t29;
t40 = phi1.*t34;
t41 = phi2.*t34;
t42 = phi3.*t34;
t47 = t29-1.0;
t48 = -t34;
t49 = t2.*t5.*t29;
t50 = t2.*t5.*t24.*t26;
t76 = phi1.*t2.*t5.*t21.*t27.*2.0;
t77 = phi2.*t2.*t5.*t21.*t27.*2.0;
t78 = phi3.*t2.*t5.*t21.*t27.*2.0;
t85 = t2.*t5.*t8.*t21.*t27.*2.0;
t86 = t2.*t5.*t9.*t21.*t27.*2.0;
t87 = t2.*t5.*t10.*t21.*t27.*2.0;
t35 = phi1.*t30;
t36 = phi2.*t30;
t37 = phi3.*t30;
t46 = -t30;
t56 = -t40;
t57 = -t41;
t58 = -t42;
t59 = phi1.*t50;
t60 = phi2.*t50;
t61 = phi3.*t50;
t68 = t2.*t5.*t38;
t69 = -t50;
t80 = t9.*t50;
t81 = t10.*t50;
t82 = phi2.*t76;
t83 = phi3.*t76;
t84 = phi3.*t77;
t90 = -t85;
t92 = phi2.*t20.*t47;
t93 = phi3.*t20.*t47;
t97 = phi1.*t20.*t47.*2.0;
t103 = phi1.*phi2.*t2.*t5.*t21.*t47.*2.0;
t104 = phi1.*phi3.*t2.*t5.*t21.*t47.*2.0;
t105 = phi2.*phi3.*t2.*t5.*t21.*t47.*2.0;
t109 = t2.*t5.*t8.*t21.*t47.*2.0;
t110 = t2.*t5.*t9.*t21.*t47.*2.0;
t111 = t2.*t5.*t10.*t21.*t47.*2.0;
t39 = t35.*2.0;
t43 = phi2.*t35;
t44 = phi3.*t35;
t45 = phi3.*t36;
t51 = -t36;
t52 = -t37;
t65 = phi2.*t59;
t66 = phi3.*t59;
t67 = phi3.*t60;
t70 = t8.*t46;
t71 = t9.*t46;
t72 = t10.*t46;
t73 = -t59;
t74 = -t60;
t75 = -t61;
t89 = t8.*t69;
t94 = phi1.*t92;
t95 = phi1.*t93;
t96 = phi3.*t92;
t98 = -t92;
t99 = -t93;
t112 = -t103;
t113 = -t104;
t114 = -t105;
t115 = -t109;
t116 = -t110;
t117 = -t111;
t134 = t34+t69;
t144 = t68+t80+t86;
t145 = t68+t81+t87;
t62 = -t43;
t63 = -t44;
t64 = -t45;
t100 = t25+t70;
t101 = t25+t71;
t102 = t25+t72;
t119 = t31+t45;
t120 = t32+t44;
t121 = t33+t43;
t135 = phi1.*phi2.*t20.*t134;
t136 = phi1.*phi3.*t20.*t134;
t137 = phi2.*phi3.*t20.*t134;
t138 = t8.*t20.*t134;
t139 = t9.*t20.*t134;
t140 = t10.*t20.*t134;
t106 = Gx.*t100;
t107 = Gy.*t101;
t108 = Gz.*t102;
t122 = Gx.*t120;
t123 = Gy.*t121;
t124 = Gz.*t119;
t141 = -t135;
t142 = -t136;
t143 = -t137;
t170 = t48+t50+t116+t139;
t171 = t48+t50+t117+t140;
t174 = t46+t59+t76+t114+t137;
t179 = t48+t50+t97+t115+t138;
t180 = t61+t78+t92+t112+t135;
t181 = t60+t77+t93+t113+t136;
t129 = -t122;
t131 = -t123;
t133 = -t124;
t175 = t46+t59+t76+t105+t143;
t185 = t61+t78+t98+t103+t141;
t186 = t60+t77+t99+t104+t142;
et1 = (Gy.*(t29+t40+t73+t67+t84)+Gz.*(t145)+Gx.*(t52+t57+t60+t66+t83)).*1.0./sqrt((t131+Gz.*(t32+t63)+t106).^2+(Gx.*(t33+t62)+t133+t107).^2+(t129+Gy.*(t31+t64)+t108).^2);
et2 = ((Gz.*(t38+t56+t59+t67+t84)+Gy.*(t144)+Gx.*(t51+t42+t75+t65+t82)).*(Gx.*(t33+t62)+t133+t107).*2.0+(Gy.*(t29+t40+t73+t67+t84)+Gz.*(t145)+Gx.*(t52+t57+t60+t66+t83)).*(t129+Gy.*(t31+t64)+t108).*2.0+(Gy.*(t51+t58+t61+t65+t82)+Gz.*(t52+t41+t74+t66+t83)-Gx.*(t39+t49+t90+t89)).*(t131+Gz.*(t32+t63)+t106).*2.0).*(t129+Gy.*(t31+t64)+t108).*1.0./((t131+Gz.*(t32+t63)+t106).^2+(Gx.*(t33+t62)+t133+t107).^2+(t129+Gy.*(t31+t64)+t108).^2).^(3.0./2.0).*(-1.0./2.0);
et3 = -(rho2.*t170+rho3.*t174-rho1.*t185).*(t107+t133+Gx.*(t33+t62))-(-rho2.*t175+rho3.*(t171)+rho1.*(t181)).*(t129+Gy.*(t31+t64)+t108)-(t131+Gz.*(t32+t63)+t106).*(rho1.*(t179)+rho2.*(t180)-rho3.*(t186))+(Gy.*(t51+t58+t61+t65+t82)+Gz.*(t52+t41+t74+t66+t83)-Gx.*(t39+t49+t90+t89)).*(rho1.*(t29-t8.*t20.*t47)+rho2.*(t37+-1.0.*t94)-rho3.*(t36+t95))+(rho2.*(t29-t9.*t20.*t47)-rho1.*(t37+t94)+rho3.*(t35+-1.0.*t96)).*(Gz.*(t38+t56+t59+t67+t84)+Gy.*(t144)+Gx.*(t51+t42+t75+t65+t82));
et4 = (rho3.*(t29-t10.*t20.*t47)+rho1.*(t36+-1.0.*t95)-rho2.*(t35+t96)).*(Gy.*(t29+t40+t73+t67+t84)+Gz.*(t145)+Gx.*(t52+t57+t60+t66+t83));
if ~all(cellfun(@isscalar,{t28,t88,t91}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t28)
    t0 = 0.0;
elseif (t28 & t91)
    t0 = (Gx.*(Gy.*t144+Gx.*(t42+t51+t65+t75+t82)+Gz.*(t38+t56+t59+t67+t84)))./(t6+(t107+t133+Gx.*(t33+t62)).^2);
elseif (1.0 < t88)
    t0 = (((Gy.*t144+Gx.*(t42+t51+t65+t75+t82)+Gz.*(t38+t56+t59+t67+t84))./(t106+t131+Gz.*(t32+t63))-(t107+t133+Gx.*(t33+t62)).*1.0./(t106+t131+Gz.*(t32+t63)).^2.*(Gy.*(t51+t58+t61+t65+t82)+Gz.*(t41+t52+t66+t74+t83)-Gx.*(t39+t49+t89+t90))).*(t106+t131+Gz.*(t32+t63)).^2)./((t107+t133+Gx.*(t33+t62)).^2+(t106+t131+Gz.*(t32+t63)).^2);
else
    t0 = NaN;
end
mt1 = [t0];
if ~all(cellfun(@isscalar,{t28,t88,t91}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t28)
    t0 = 0.0;
elseif (t28 & t91)
    t0 = (Gz.*(Gz.*t145+Gx.*(t52+t57+t60+t66+t83)+Gy.*(t29+t40+t67+t73+t84)).*(t108+t129+Gy.*(t31+t64)).*1.0./(t6+t7+(t108+t129+Gy.*(t31+t64)).^2).^(3.0./2.0))./conj(sqrt(-Gz.^2./(t6+t7+(t108+t129+Gy.*(t31+t64)).^2)+1.0));
elseif (1.0 < t88)
    t0 = -(et1+et2)./conj(sqrt(-(t108+t129+Gy.*(t31+t64)).^2./((t107+t133+Gx.*(t33+t62)).^2+(t108+t129+Gy.*(t31+t64)).^2+(t106+t131+Gz.*(t32+t63)).^2)+1.0));
else
    t0 = NaN;
end
mt2 = [t0];
if ~all(cellfun(@isscalar,{t28,t88}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t28)
    t0 = -Gx.*(rho1.*t179+rho2.*t180-rho3.*t186)-Gy.*(rho2.*t170+rho3.*t174-rho1.*t185)-Gz.*(rho3.*t171-rho2.*t175+rho1.*t181);
elseif (1.0 < t88)
    t0 = et3+et4;
else
    t0 = NaN;
end
mt3 = [t0];
d_tau_d_phi1 = [mt1;mt2;mt3];
end
