function d_tau_d_rho3 = d_tau_d_rho3(rho1,rho2,rho3,phi1,phi2,phi3,Gx,Gy,Gz)
%D_TAU_D_RHO3
%    D_TAU_D_RHO3 = D_TAU_D_RHO3(RHO1,RHO2,RHO3,PHI1,PHI2,PHI3,Gx,Gy,Gz)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-Oct-2024 18:56:12

t2 = abs(phi1);
t3 = abs(phi2);
t4 = abs(phi3);
t5 = phi1.^2;
t6 = phi1.^3;
t7 = phi2.^2;
t8 = phi2.^3;
t9 = phi3.^2;
t10 = phi3.^3;
t11 = t2.^2;
t12 = t3.^2;
t13 = t4.^2;
t14 = -t5;
t15 = -t7;
t16 = -t9;
t17 = t5+t7+t9;
t18 = 1.0./t17;
t19 = t11+t12+t13;
t25 = t14+t15+t16;
t20 = 1.0./t19;
t21 = sqrt(t19);
t27 = sqrt(t25);
t22 = 1.0./t21;
t23 = cos(t21);
t24 = sin(t21);
t28 = t27.^3;
t29 = conj(t27);
t26 = t23-1.0;
t30 = conj(t28);
t31 = exp(t29);
t32 = -t29;
t35 = phi1.*phi2.*t29.*2.0;
t49 = t22.*t24;
t33 = 1.0./t30;
t34 = exp(t32);
t36 = t5.*t31;
t37 = t7.*t31;
t38 = t9.*t31;
t39 = t10.*t31;
t40 = -t35;
t50 = t49-1.0;
t51 = phi1.*phi2.*t29.*t31;
t41 = phi3.*t36;
t42 = phi3.*t37;
t43 = t5.*t34;
t44 = t7.*t34;
t45 = t9.*t34;
t46 = t10.*t34;
t52 = phi1.*phi2.*t29.*t34;
t47 = phi3.*t43;
t48 = phi3.*t44;
et1 = -(phi2.*t20.*t26+phi1.*phi3.*t20.*t50).*((Gx.*t18.*(t5.*2.0+t37+t38+t44+t45))./2.0+(Gy.*t33.*(t39+t40+t41+t42-t46+t51+t52+phi3.*t14.*t34+phi3.*t15.*t34))./2.0-(Gz.*t18.*(phi1.*phi3.*-2.0+phi1.*phi3.*t31+phi1.*phi3.*t34+phi2.*t29.*t31+phi2.*t32.*t34))./2.0)+(phi1.*t20.*t26-phi2.*phi3.*t20.*t50).*((Gy.*t18.*(t7.*2.0+t36+t38+t43+t45))./2.0+(Gx.*t33.*(-t39+t40+t46+t47+t48+t51+t52+phi3.*t14.*t31+phi3.*t15.*t31))./2.0-(Gz.*t18.*(phi2.*phi3.*-2.0+phi2.*phi3.*t31+phi2.*phi3.*t34+phi1.*t29.*t34+phi1.*t31.*t32))./2.0);
et2 = (t49+t16.*t20.*t50).*((Gx.*t33.*(phi2.*t36+phi2.*t38+t8.*t31-t8.*t34-phi1.*phi3.*t29.*2.0+phi2.*t14.*t34+phi2.*t16.*t34+phi1.*phi3.*t29.*t31+phi1.*phi3.*t29.*t34))./2.0+(Gy.*t33.*(phi1.*t44+phi1.*t45-t6.*t31+t6.*t34-phi2.*phi3.*t29.*2.0+phi1.*t15.*t31+phi1.*t16.*t31+phi2.*phi3.*t29.*t31+phi2.*phi3.*t29.*t34))./2.0+(Gz.*t18.*(t9.*2.0+t36+t37+t43+t44))./2.0);
if ~all(cellfun(@isscalar,{phi1,phi2,phi3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (((phi1 ~= 0.0) | (phi2 ~= 0.0)) | (phi3 ~= 0.0))
    t0 = 0.0;
else
    t0 = NaN;
end
d_tau_d_rho3 = [t0;0.0;et1+et2];
end
