function d_tau_d_rho2 = d_tau_d_rho2(rho1,rho2,rho3,phi1,phi2,phi3,Gx,Gy,Gz)
%D_TAU_D_RHO2
%    D_TAU_D_RHO2 = D_TAU_D_RHO2(RHO1,RHO2,RHO3,PHI1,PHI2,PHI3,Gx,Gy,Gz)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    22-Oct-2024 02:10:04

t2 = abs(phi1);
t3 = abs(phi2);
t4 = abs(phi3);
t5 = phi1.^2;
t6 = phi2.^2;
t7 = phi3.^2;
t8 = t2.^2;
t9 = t3.^2;
t10 = t4.^2;
t11 = t5+t6+t7;
t12 = t8+t9+t10;
t13 = sqrt(t11);
t34 = t11.*1.0e+10;
t17 = 1.0./t12;
t18 = sqrt(t12);
t23 = (t13 < 1.0e-5);
t35 = (1.0 <= t34);
t19 = 1.0./t18;
t20 = cos(t18);
t21 = sin(t18);
if ~all(cellfun(@isscalar,{t23,t35}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t23 | t35)
    t42 = 0.0;
else
    t42 = NaN;
end
t22 = t20-1.0;
t24 = t19.*t21;
t25 = phi1.*t24;
t26 = phi2.*t24;
t27 = phi3.*t24;
t28 = phi1.*t17.*t22;
t29 = phi3.*t17.*t22;
t33 = t24-1.0;
t30 = phi2.*t28;
t31 = phi3.*t28;
t32 = phi2.*t29;
t36 = phi1.*phi2.*t17.*t33;
t37 = phi2.*phi3.*t17.*t33;
t38 = t6.*t17.*t33;
t39 = -t36;
t40 = -t38;
t43 = t28+t37;
t44 = t24+t40;
t45 = t29+t39;
if ~all(cellfun(@isscalar,{t23,t34}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t23)
    t0 = Gx.*t45+Gy.*t44-Gz.*t43;
elseif (1.0 <= t34)
    t0 = -t43.*(Gz.*(t20-t7.*t17.*t22)+Gy.*(t25-t32)-Gx.*(t26+t31))+t44.*(Gy.*(t20-t6.*t17.*t22)+Gx.*(t27-t30)-Gz.*(t25+t32))+t45.*(Gx.*(t20-t5.*t17.*t22)+Gz.*(t26-t31)-Gy.*(t27+t30));
else
    t0 = NaN;
end
d_tau_d_rho2 = [t42;t42;t0];
end
